export const SCALE_OPTIONS = [
  { value: 1, label: '1', shortLabel: 'Not in place', description: 'No meaningful capability or process exists.' },
  { value: 2, label: '2', shortLabel: 'Minimal', description: 'Limited or ad hoc activity with low consistency.' },
  { value: 3, label: '3', shortLabel: 'Emerging', description: 'Some structure exists but adoption remains uneven.' },
  { value: 4, label: '4', shortLabel: 'Established', description: 'Operationally embedded with defined ownership.' },
  { value: 5, label: '5', shortLabel: 'Strong', description: 'Mature, aligned, and dependable across the organization.' },
  { value: 'not_sure', label: '?', shortLabel: 'Not sure', description: 'Use when the answer is unclear or unavailable.' },
];

export const CATEGORY_WEIGHTS = {
  strategyVision: 0.15,
  leadershipGovernance: 0.15,
  dataReadiness: 0.15,
  technologyInfrastructure: 0.1,
  securityRiskCompliance: 0.15,
  peopleSkillsChange: 0.1,
  workflowIntegration: 0.1,
  trustEthicsHuman: 0.1,
};

export const MATURITY_LEVELS = [
  {
    key: 'unprepared',
    min: 1,
    max: 24,
    label: 'Unprepared',
    summary: 'AI interest may exist, but the organizational conditions required for responsible execution are not yet in place.',
    strengths: 'Early awareness and potential executive curiosity can become a foundation if paired with structure.',
    warning: 'Launching pilots at this stage risks fragmented effort, policy exposure, and low trust.',
  },
  {
    key: 'early',
    min: 25,
    max: 49,
    label: 'Early',
    summary: 'The organization is beginning to explore AI, but readiness is inconsistent across leadership, systems, and operating disciplines.',
    strengths: 'There is enough momentum to define priorities and begin targeted capability-building.',
    warning: 'Without alignment and governance, experimentation can outpace control and measurable value.',
  },
  {
    key: 'emerging',
    min: 50,
    max: 69,
    label: 'Emerging',
    summary: 'Core readiness is taking shape. The organization can likely support selective AI initiatives with the right guardrails.',
    strengths: 'Leadership intent and practical execution pathways are starting to connect.',
    warning: 'Gaps in data, change management, or governance may still prevent scaling.',
  },
  {
    key: 'capable',
    min: 70,
    max: 84,
    label: 'Capable',
    summary: 'The organization has a credible base for disciplined AI adoption and can move from pilots toward operational integration.',
    strengths: 'Cross-functional readiness is evident, creating favorable conditions for responsible execution.',
    warning: 'The next challenge is consistency, measurement, and sustained executive sponsorship.',
  },
  {
    key: 'leading',
    min: 85,
    max: 100,
    label: 'Leading',
    summary: 'AI readiness is advanced, strategically integrated, and supported by mature governance, infrastructure, and trust mechanisms.',
    strengths: 'The organization is positioned to scale AI responsibly and differentiate through disciplined adoption.',
    warning: 'The key risk is complacency; leaders at this stage should continue evolving standards, controls, and workforce capability.',
  },
];

export const ARCHETYPES = [
  {
    key: 'cautious-explorer',
    label: 'Cautious Explorer',
    description: 'Interested in AI, but still building the confidence, controls, and business case needed for broader adoption.',
  },
  {
    key: 'fragmented-experimenter',
    label: 'Fragmented Experimenter',
    description: 'Energy and pilots exist, but execution is uneven and not yet governed by a clear operating model.',
  },
  {
    key: 'operational-builder',
    label: 'Operational Builder',
    description: 'The organization is translating AI intent into real workflows and managed capabilities.',
  },
  {
    key: 'strategic-leader',
    label: 'Strategic Leader',
    description: 'AI adoption is aligned to enterprise priorities and managed with operational and ethical discipline.',
  },
];

export const ASSESSMENT_CATEGORIES = [
  {
    id: 'strategyVision',
    title: 'Strategy & Vision',
    shortTitle: 'Strategy',
    weight: CATEGORY_WEIGHTS.strategyVision,
    description: 'Clarifies whether AI is connected to organizational priorities, business outcomes, and executive intent.',
    questions: [
      { id: 'sv1', prompt: 'Leadership has articulated a clear reason the organization is pursuing AI.' },
      { id: 'sv2', prompt: 'AI priorities are tied to measurable business, mission, or operational outcomes.' },
      { id: 'sv3', prompt: 'There is alignment across senior leaders on where AI should and should not be used.' },
      { id: 'sv4', prompt: 'The organization can distinguish strategic AI initiatives from opportunistic experimentation.' },
      { id: 'sv5', prompt: 'AI efforts are being prioritized against a broader roadmap rather than isolated requests.' },
    ],
  },
  {
    id: 'leadershipGovernance',
    title: 'Leadership & Governance',
    shortTitle: 'Governance',
    weight: CATEGORY_WEIGHTS.leadershipGovernance,
    description: 'Measures ownership, decision rights, and the extent to which AI is governed as an enterprise capability.',
    questions: [
      { id: 'lg1', prompt: 'An executive or leadership group is clearly accountable for AI direction and outcomes.' },
      { id: 'lg2', prompt: 'Decision rights are defined for tool selection, vendor review, and use-case approval.' },
      { id: 'lg3', prompt: 'There are emerging or established policies for acceptable AI use.' },
      { id: 'lg4', prompt: 'Cross-functional stakeholders can coordinate on AI-related decisions without confusion.' },
      { id: 'lg5', prompt: 'AI initiatives are reviewed with enough rigor before moving into production or scale.' },
    ],
  },
  {
    id: 'dataReadiness',
    title: 'Data Readiness',
    shortTitle: 'Data',
    weight: CATEGORY_WEIGHTS.dataReadiness,
    description: 'Evaluates whether data quality, accessibility, integration, and stewardship can support useful AI adoption.',
    questions: [
      { id: 'dr1', prompt: 'Key data needed for AI use cases is accessible to the right teams.' },
      { id: 'dr2', prompt: 'The organization has reasonable confidence in the quality and consistency of core data.' },
      { id: 'dr3', prompt: 'Important systems are integrated enough to support cross-functional AI workflows.' },
      { id: 'dr4', prompt: 'Sensitive data is classified and handled in a way that supports responsible AI use.' },
      { id: 'dr5', prompt: 'Known data gaps or fragmentation issues are visible and being actively addressed.' },
    ],
  },
  {
    id: 'technologyInfrastructure',
    title: 'Technology & Infrastructure',
    shortTitle: 'Technology',
    weight: CATEGORY_WEIGHTS.technologyInfrastructure,
    description: 'Assesses whether the organization has a usable technical foundation for AI pilots and integrations.',
    questions: [
      { id: 'ti1', prompt: 'Core systems are modern enough to support AI-enabled workflows without major disruption.' },
      { id: 'ti2', prompt: 'The organization has access to APIs, automation tools, or integration layers needed for experimentation.' },
      { id: 'ti3', prompt: 'Cloud, security, and infrastructure practices can support AI pilots in a controlled manner.' },
      { id: 'ti4', prompt: 'The technical environment can absorb new AI tools without creating significant operational chaos.' },
    ],
  },
  {
    id: 'securityRiskCompliance',
    title: 'Security, Risk & Compliance',
    shortTitle: 'Risk',
    weight: CATEGORY_WEIGHTS.securityRiskCompliance,
    description: 'Determines whether AI use is being assessed through privacy, security, regulatory, and reputational lenses.',
    questions: [
      { id: 'sr1', prompt: 'AI-related privacy and security risks are reviewed before new tools or workflows are adopted.' },
      { id: 'sr2', prompt: 'The organization considers vendor risk, data handling, and contractual exposure when evaluating AI solutions.' },
      { id: 'sr3', prompt: 'There is awareness of regulatory, audit, or reputational implications tied to AI use.' },
      { id: 'sr4', prompt: 'High-risk use cases would trigger additional oversight or review.' },
      { id: 'sr5', prompt: 'There is a practical approach to logging, traceability, or documentation for AI-enabled decisions.' },
    ],
  },
  {
    id: 'peopleSkillsChange',
    title: 'People, Skills & Change Readiness',
    shortTitle: 'People',
    weight: CATEGORY_WEIGHTS.peopleSkillsChange,
    description: 'Looks at workforce capability, adoption readiness, training, and the ability to manage organizational change.',
    questions: [
      { id: 'ps1', prompt: 'Leaders can communicate AI adoption in a way that reduces confusion and fear.' },
      { id: 'ps2', prompt: 'Staff have at least a baseline understanding of responsible AI use in their roles.' },
      { id: 'ps3', prompt: 'Training, enablement, or coaching is available or planned for relevant teams.' },
      { id: 'ps4', prompt: 'The organization can identify and support internal champions for AI adoption.' },
      { id: 'ps5', prompt: 'Change management is treated as a core part of AI implementation, not an afterthought.' },
    ],
  },
  {
    id: 'workflowIntegration',
    title: 'Workflow & Operational Integration',
    shortTitle: 'Workflow',
    weight: CATEGORY_WEIGHTS.workflowIntegration,
    description: 'Measures whether AI is linked to real workflows, value creation, and operational measurement.',
    questions: [
      { id: 'wi1', prompt: 'The organization has identified specific workflows where AI could improve quality, speed, or cost.' },
      { id: 'wi2', prompt: 'Potential AI use cases are being prioritized based on business value and feasibility.' },
      { id: 'wi3', prompt: 'There are clear owners for embedding AI into actual operating processes.' },
      { id: 'wi4', prompt: 'Success measures exist or could be defined for AI-enabled workflow improvements.' },
      { id: 'wi5', prompt: 'The organization can pilot AI in targeted workflows without losing accountability.' },
    ],
  },
  {
    id: 'trustEthicsHuman',
    title: 'Trust, Ethics & Human-Centered Design',
    shortTitle: 'Trust & Ethics',
    weight: CATEGORY_WEIGHTS.trustEthicsHuman,
    description: 'Checks whether human oversight, fairness, transparency, and trust are part of the adoption model.',
    questions: [
      { id: 'te1', prompt: 'The organization considers fairness, transparency, and accountability when evaluating AI use.' },
      { id: 'te2', prompt: 'There is clarity on when human review or approval must remain in the loop.' },
      { id: 'te3', prompt: 'Stakeholders are thinking about trust and stakeholder impact, not just automation efficiency.' },
      { id: 'te4', prompt: 'Leaders would be able to explain how AI-assisted decisions are made in sensitive contexts.' },
      { id: 'te5', prompt: 'There is awareness that some use cases may be inappropriate even if technically possible.' },
    ],
  },
];
