import { ASSESSMENT_CATEGORIES } from './assessment-config';

function cloneBaseCategories() {
  return ASSESSMENT_CATEGORIES.map((category) => ({
    ...category,
    questions: category.questions.map((question) => ({ ...question })),
  }));
}

function replacePrompts(categories, promptMap) {
  return categories.map((category) => ({
    ...category,
    questions: category.questions.map((question) => ({
      ...question,
      prompt: promptMap[question.id] || question.prompt,
    })),
  }));
}

const educationalPrompts = {
  sv1: 'Institutional leadership has articulated a clear reason for adopting AI in teaching, operations, learner support, or community communication.',
  sv2: 'AI priorities are tied to measurable educational, administrative, or community outcomes.',
  sv3: 'Senior leaders are aligned on where AI should and should not be used across the institution.',
  sv4: 'The institution can distinguish strategic AI opportunities from opportunistic experimentation.',
  sv5: 'AI efforts are being prioritized against an institutional roadmap rather than isolated requests.',
  lg1: 'A school, district, or institutional leader is clearly accountable for AI direction and outcomes.',
  lg2: 'Decision rights are clear for tool approval, pilot selection, and learner/staff-facing use cases.',
  lg3: 'There are emerging or established expectations for acceptable AI use by faculty, staff, and leadership.',
  lg4: 'Academic, operational, and technology stakeholders can coordinate on AI-related decisions without confusion.',
  lg5: 'AI initiatives are reviewed with enough rigor before being expanded across classrooms, departments, or campuses.',
  dr1: 'Key learner, staff, and operational data needed for AI use cases is accessible to the right teams.',
  dr2: 'The institution has reasonable confidence in the quality and consistency of core student, staff, or operational data.',
  dr3: 'Important systems are integrated enough to support AI workflows across instruction, administration, and communication.',
  dr4: 'Learner, staff, and sensitive institutional data are handled in ways that support responsible AI use.',
  dr5: 'Known data fragmentation or quality issues are visible and being addressed before AI use expands.',
  ti1: 'Core academic and administrative systems are modern enough to support AI-enabled workflows without major disruption.',
  ti2: 'The institution has access to approved tools, platforms, or integrations needed for controlled experimentation.',
  ti3: 'Infrastructure, access, and support practices can support AI pilots in a controlled and equitable way.',
  ti4: 'The technical environment can absorb new AI tools without creating major support, access, or workflow chaos.',
  sr1: 'AI-related privacy and security risks are reviewed before learner, staff, or operational tools are adopted.',
  sr2: 'The institution considers vendor risk, data handling, and records obligations when evaluating AI solutions.',
  sr3: 'There is awareness of regulatory, reputational, and community trust implications tied to AI use.',
  sr4: 'High-risk educational or learner-facing use cases would trigger additional oversight or review.',
  sr5: 'There is a practical approach to documentation, traceability, or review for AI-enabled decisions and workflows.',
  ps1: 'Institutional leaders can communicate AI adoption in a way that reduces fear and builds confidence.',
  ps2: 'Faculty and staff have at least a baseline understanding of responsible AI use in their roles.',
  ps3: 'Training or enablement is available or planned for the people expected to use AI in educational or operational workflows.',
  ps4: 'The institution can identify and support internal champions for responsible AI adoption.',
  ps5: 'Change management is treated as a core part of AI implementation, not an afterthought.',
  wi1: 'The institution has identified workflows where AI could improve teaching support, communication, advising, administration, or planning.',
  wi2: 'Potential AI use cases are prioritized based on educational value, feasibility, and trust implications.',
  wi3: 'There are clear owners for embedding AI into academic, administrative, or communication processes.',
  wi4: 'Success measures exist or could be defined for AI-enabled improvements in institutional workflows.',
  wi5: 'The institution can pilot AI in targeted workflows without losing accountability or community trust.',
  te1: 'The institution considers fairness, transparency, and accountability when evaluating AI use.',
  te2: 'There is clarity on when human review must remain in the loop for learner-facing or high-sensitivity decisions.',
  te3: 'Leaders are thinking about trust, learner impact, and community confidence — not just efficiency.',
  te4: 'Institutional leaders would be able to explain how AI-assisted decisions are made in sensitive contexts.',
  te5: 'There is awareness that some AI use cases may be inappropriate in educational settings even if technically possible.',
};

const nonprofitPrompts = {
  sv1: 'Leadership has articulated a clear reason for using AI to strengthen mission delivery, fundraising, communications, or internal capacity.',
  sv2: 'AI priorities are tied to measurable mission, program, fundraising, or staff-capacity outcomes.',
  sv3: 'Leadership is aligned on where AI should and should not be used in mission-critical work.',
  sv4: 'The organization can distinguish meaningful AI opportunities from distraction or hype.',
  sv5: 'AI efforts are being prioritized against mission and capacity realities rather than isolated requests.',
  lg1: 'An executive or leadership group is clearly accountable for AI direction and mission-aligned outcomes.',
  lg2: 'Decision rights are defined for tool selection, vendor review, and mission-sensitive use-case approval.',
  lg3: 'There are lightweight but clear expectations for acceptable AI use across the organization.',
  lg4: 'Program, operations, fundraising, and leadership stakeholders can coordinate on AI-related decisions without confusion.',
  lg5: 'AI initiatives are reviewed with enough rigor before becoming part of normal operations.',
  dr1: 'Key donor, program, and operational data needed for AI use cases is accessible to the right teams.',
  dr2: 'The organization has reasonable confidence in the quality and consistency of donor, program, or operational data.',
  dr3: 'Important systems are integrated enough to support practical AI workflows across teams.',
  dr4: 'Sensitive donor, beneficiary, and internal data is handled in ways that support responsible AI use.',
  dr5: 'Known data fragmentation or quality issues are visible and being actively addressed.',
  ti1: 'Core systems are modern enough to support AI-enabled workflows without creating major disruption.',
  ti2: 'The organization has access to practical tools or integrations needed for responsible experimentation.',
  ti3: 'The technical environment can support AI pilots without overwhelming limited internal capacity.',
  ti4: 'The organization can absorb new AI tools without creating major workflow or support confusion.',
  sr1: 'AI-related privacy and security risks are reviewed before new tools or workflows are adopted.',
  sr2: 'The organization considers vendor risk, data handling, and trust implications when evaluating AI tools.',
  sr3: 'There is awareness of stewardship, reputational, and community trust implications tied to AI use.',
  sr4: 'High-risk donor, beneficiary, or public-facing use cases would trigger additional oversight or review.',
  sr5: 'There is a practical approach to reviewing or documenting important AI-enabled decisions and workflows.',
  ps1: 'Leaders can communicate AI adoption in a way that reduces fear and keeps mission at the center.',
  ps2: 'Staff have at least a baseline understanding of responsible AI use in their roles.',
  ps3: 'Practical training or guidance exists so the team can use AI responsibly and effectively.',
  ps4: 'The organization can identify and support internal champions for AI adoption.',
  ps5: 'Change management is treated as part of AI implementation, even in a lean-team environment.',
  wi1: 'The organization has identified workflows where AI could improve program support, communications, fundraising, research, or internal operations.',
  wi2: 'Potential AI use cases are prioritized based on mission value, feasibility, and trust implications.',
  wi3: 'There are clear owners for embedding AI into actual operating processes.',
  wi4: 'Success measures exist or could be defined for AI-enabled workflow improvements.',
  wi5: 'The organization can pilot AI in targeted workflows without losing accountability or mission trust.',
  te1: 'The organization considers fairness, transparency, accountability, and trust when evaluating AI use.',
  te2: 'There is clarity on when human review must remain in the loop for beneficiary-facing or sensitive decisions.',
  te3: 'Leaders are thinking about trust, dignity, and stakeholder impact — not just efficiency.',
  te4: 'Leadership would be able to explain how AI-assisted decisions are made in mission-sensitive contexts.',
  te5: 'There is awareness that some AI use cases may be inappropriate for mission-driven work even if technically possible.',
};

const smallBusinessPrompts = {
  sv1: 'Business leadership has a clear reason for using AI in daily operations, customer communication, sales, marketing, or internal admin.',
  sv2: 'AI priorities are tied to measurable outcomes such as time savings, faster response times, stronger marketing output, or revenue support.',
  sv3: 'Leadership is aligned on where AI should and should not be used in the business.',
  sv4: 'The business can distinguish practical AI opportunities from distracting experiments.',
  sv5: 'AI efforts are prioritized against business needs rather than random tool adoption.',
  lg1: 'An owner or leader is clearly accountable for AI direction and outcomes.',
  lg2: 'Decision rights are clear enough that staff know which tools are approved and how they should be used.',
  lg3: 'There are simple expectations or guardrails for acceptable AI use in the business.',
  lg4: 'Teams can coordinate on AI-related decisions without confusion or duplicated tool sprawl.',
  lg5: 'New AI tools or workflows are reviewed before becoming part of normal operations.',
  dr1: 'Key customer, operational, and internal business data needed for AI use cases is accessible to the right people.',
  dr2: 'The business has reasonable confidence in the quality and consistency of its core information.',
  dr3: 'Important systems are connected enough to support useful AI-enabled workflows.',
  dr4: 'Sensitive customer, financial, or internal data is handled in ways that support responsible AI use.',
  dr5: 'Known data gaps or inconsistencies are visible and being addressed.',
  ti1: 'Core systems and tools are modern enough to support AI-enabled workflows without major disruption.',
  ti2: 'The business has access to practical tools, automation, or integrations needed for experimentation.',
  ti3: 'The business can support AI pilots without creating unnecessary complexity or overhead.',
  ti4: 'The technical environment can absorb new AI tools without creating major confusion or workflow disruption.',
  sr1: 'AI-related privacy and security risks are considered before new tools or workflows are adopted.',
  sr2: 'The business considers vendor risk, data handling, and customer exposure when evaluating AI tools.',
  sr3: 'There is awareness of reputational, legal, or operational exposure tied to AI use.',
  sr4: 'Higher-risk customer, financial, or sensitive use cases would trigger additional review.',
  sr5: 'There is at least a practical approach to reviewing or documenting important AI-enabled actions.',
  ps1: 'Leaders can communicate AI adoption in a way that reduces confusion and resistance.',
  ps2: 'Staff have at least a baseline understanding of responsible AI use in their roles.',
  ps3: 'Simple training or guidance exists so the team can use AI effectively and responsibly.',
  ps4: 'The business can identify and support internal AI adopters or champions.',
  ps5: 'Change management is treated as a real part of AI implementation, even in a small-team environment.',
  wi1: 'The business has identified specific workflows where AI could improve speed, responsiveness, quality, or consistency.',
  wi2: 'AI use cases are being prioritized based on practical business value and ease of implementation.',
  wi3: 'There are clear owners for embedding AI into actual day-to-day business processes.',
  wi4: 'Success measures exist or could be defined for AI-enabled workflow improvements.',
  wi5: 'The business can pilot AI in targeted workflows without losing accountability.',
  te1: 'The business considers trust, transparency, and accountability when evaluating AI use.',
  te2: 'There is clarity on when people must stay in the loop for customer-facing, financial, or sensitive decisions.',
  te3: 'Leaders think about customer trust and business reputation, not just automation efficiency.',
  te4: 'The business could explain how AI-assisted work is being used in important customer or internal processes.',
  te5: 'There is awareness that some AI use cases may be inappropriate even if technically possible.',
};

const itTeamPrompts = {
  sv1: 'Technology leadership has articulated a clear reason for supporting AI across enterprise, service, automation, or internal support workflows.',
  sv2: 'AI priorities are tied to measurable improvements in service delivery, automation, governance, support efficiency, or enterprise enablement.',
  sv3: 'Leadership is aligned on where AI should and should not be used across the technical environment.',
  sv4: 'The team can distinguish strategic AI opportunities from low-value experimentation or tool sprawl.',
  sv5: 'AI efforts are prioritized against an operational roadmap rather than ad hoc requests.',
  lg1: 'A CIO, CTO, IT leader, or governance group is clearly accountable for AI direction and outcomes.',
  lg2: 'Decision rights are defined for approved tools, vendor review, use-case approval, and technical ownership.',
  lg3: 'There are emerging or established policies for acceptable AI use across internal technology environments.',
  lg4: 'Security, infrastructure, operations, and business stakeholders can coordinate on AI-related decisions without confusion.',
  lg5: 'AI initiatives are reviewed with enough rigor before moving into production or broad enablement.',
  dr1: 'Key enterprise, operational, and support data needed for AI use cases is accessible to the right teams.',
  dr2: 'The organization has reasonable confidence in the quality and consistency of core systems data.',
  dr3: 'Important systems are integrated enough to support cross-functional AI workflows without weakening governance.',
  dr4: 'Sensitive enterprise and internal data are classified and handled in ways that support responsible AI use.',
  dr5: 'Known data fragmentation, logging, or lineage issues are visible and being actively addressed.',
  ti1: 'Core systems are modern enough to support AI-enabled workflows without major operational disruption.',
  ti2: 'The organization has access to APIs, automation tools, cloud platforms, or integration layers needed for controlled experimentation.',
  ti3: 'Infrastructure, security, and platform practices can support AI pilots in a controlled manner.',
  ti4: 'The technical environment can absorb new AI tools without creating unsustainable support or governance burden.',
  sr1: 'AI-related privacy and security risks are reviewed before new tools or workflows are adopted.',
  sr2: 'The team considers vendor risk, data handling, access control, and contractual exposure when evaluating AI solutions.',
  sr3: 'There is awareness of regulatory, audit, and reputational implications tied to AI use.',
  sr4: 'High-risk enterprise use cases would trigger additional oversight or review.',
  sr5: 'There is a practical approach to logging, traceability, or documentation for AI-enabled decisions and workflows.',
  ps1: 'Technology leaders can communicate AI adoption in a way that reduces confusion and shadow-IT behavior.',
  ps2: 'Technical teams and adjacent stakeholders have at least a baseline understanding of responsible AI use in their roles.',
  ps3: 'Training, enablement, or guidance is available or planned for teams expected to support or use AI.',
  ps4: 'The organization can identify and support technical champions for AI adoption.',
  ps5: 'Change management is treated as part of AI enablement rather than a downstream cleanup exercise.',
  wi1: 'The IT organization has identified workflows where AI could improve service desk, automation, documentation, reporting, or support operations.',
  wi2: 'Potential AI use cases are prioritized based on operational value, feasibility, and governance requirements.',
  wi3: 'There are clear owners for embedding AI into actual support, automation, or enterprise workflows.',
  wi4: 'Success measures exist or could be defined for AI-enabled workflow improvements in technical and enterprise operations.',
  wi5: 'The organization can pilot AI in targeted workflows without losing accountability, auditability, or supportability.',
  te1: 'The organization considers fairness, transparency, accountability, and reviewability when evaluating AI use.',
  te2: 'There is clarity on when human approval or escalation must remain in the loop for sensitive workflows.',
  te3: 'Leaders are thinking about trust, control, and governance — not just speed and automation.',
  te4: 'Technical leadership would be able to explain how AI-assisted decisions are made in sensitive operational contexts.',
  te5: 'The team recognizes that some AI use cases may be technically feasible but still inappropriate from a governance or support perspective.',
};

const creativePrompts = {
  sv1: 'Leadership has articulated a clear reason for using AI across content, ideation, design, production, or campaign workflows.',
  sv2: 'AI priorities are tied to measurable outcomes like speed, throughput, quality, or creative leverage.',
  sv3: 'Leaders are aligned on where AI should and should not be used in creative and client-facing work.',
  sv4: 'The team can distinguish strategic workflow leverage from novelty-driven experimentation.',
  sv5: 'AI efforts are prioritized against creative, operational, or client goals rather than isolated tool adoption.',
  lg1: 'A creative or operational leader is clearly accountable for AI direction and outcomes.',
  lg2: 'Decision rights are defined for approved tools, client-facing use, and workflow adoption.',
  lg3: 'There are clear expectations for acceptable AI use in drafts, production, ideation, and delivery.',
  lg4: 'Creative, account, production, and leadership teams can coordinate on AI-related decisions without confusion.',
  lg5: 'New AI workflows are reviewed before they become part of normal client or production processes.',
  dr1: 'Key brand assets, creative materials, and internal knowledge needed for AI workflows are accessible to the right teams.',
  dr2: 'The team has reasonable confidence in the quality and consistency of core assets and reference materials.',
  dr3: 'Important tools and systems are integrated enough to support AI-enabled creative workflows.',
  dr4: 'Brand assets, internal content, and client materials are handled in ways that support responsible AI use.',
  dr5: 'Known content, asset, or workflow fragmentation issues are visible and being addressed.',
  ti1: 'Core creative and production systems are modern enough to support AI-enabled workflows without major disruption.',
  ti2: 'The team has access to the tools, platforms, and integrations needed for practical experimentation.',
  ti3: 'The environment can support AI pilots without creating versioning, process, or coordination chaos.',
  ti4: 'The technical environment can absorb new AI tools without disrupting production quality or delivery workflows.',
  sr1: 'AI-related privacy and security risks are reviewed before new tools or workflows are adopted.',
  sr2: 'The team considers client confidentiality, vendor risk, and rights/IP implications when evaluating AI tools.',
  sr3: 'There is awareness of reputational, contractual, and trust implications tied to AI use.',
  sr4: 'Higher-risk client-facing or rights-sensitive use cases would trigger additional oversight or review.',
  sr5: 'There is a practical approach to reviewing or documenting important AI-enabled creative decisions and workflows.',
  ps1: 'Leaders can communicate AI adoption in a way that reduces anxiety and protects confidence in creative craft.',
  ps2: 'Creative staff have at least a baseline understanding of responsible AI use in their roles.',
  ps3: 'Training or guidance is available or planned for teams expected to use AI in creative workflows.',
  ps4: 'The organization can identify and support internal champions for AI-enabled creative operations.',
  ps5: 'Change management is treated as part of implementation, not just a side effect of new tools.',
  wi1: 'The team has identified workflows where AI could improve ideation, drafting, editing, repurposing, research, or production support.',
  wi2: 'Potential AI use cases are prioritized based on quality, efficiency, and client impact.',
  wi3: 'There are clear owners for embedding AI into actual creative or delivery processes.',
  wi4: 'Success measures exist or could be defined for AI-enabled workflow improvements.',
  wi5: 'The team can pilot AI in targeted workflows without losing quality control or accountability.',
  te1: 'The organization considers originality, transparency, accountability, and trust when evaluating AI use.',
  te2: 'There is clarity on when human review must remain in the loop for quality, originality, or client-facing outputs.',
  te3: 'Leaders think about trust, reputation, and quality — not just speed and output volume.',
  te4: 'Leadership would be able to explain how AI is used in sensitive or client-facing creative workflows.',
  te5: 'There is awareness that some AI use cases may be inappropriate for creative work even if technically possible.',
};

const professionalPrompts = {
  sv1: 'Leadership has articulated a clear reason for using AI to improve client delivery, knowledge work, research, or internal leverage.',
  sv2: 'AI priorities are tied to measurable client value, delivery quality, internal leverage, or turnaround outcomes.',
  sv3: 'Leaders are aligned on where AI should and should not be used in client-facing and internal work.',
  sv4: 'The firm can distinguish strategic AI opportunities from low-value experimentation.',
  sv5: 'AI efforts are prioritized against delivery goals and risk posture rather than isolated requests.',
  lg1: 'A firm leader or leadership group is clearly accountable for AI direction and outcomes.',
  lg2: 'Decision rights are defined for client-facing use, vendor approval, and practice-level AI workflows.',
  lg3: 'There are clear expectations for acceptable AI use in internal and client-facing work.',
  lg4: 'Practice, operations, and leadership stakeholders can coordinate on AI-related decisions without confusion.',
  lg5: 'AI initiatives are reviewed with enough rigor before becoming part of client delivery or core operations.',
  dr1: 'Key internal knowledge, templates, and relevant data needed for AI workflows are accessible to the right teams.',
  dr2: 'The firm has reasonable confidence in the quality and consistency of its core knowledge and operational data.',
  dr3: 'Important systems are integrated enough to support practical AI workflows across delivery and operations.',
  dr4: 'Client and confidential data are handled in ways that support responsible AI use.',
  dr5: 'Known knowledge, content, or data fragmentation issues are visible and being addressed.',
  ti1: 'Core systems are modern enough to support AI-enabled workflows without major disruption to delivery quality.',
  ti2: 'The firm has access to approved tools and integrations needed for controlled experimentation.',
  ti3: 'The environment can support AI pilots without creating unmanaged risk or workflow confusion.',
  ti4: 'The technical environment can absorb new AI tools without undermining review, quality, or accountability.',
  sr1: 'AI-related privacy and security risks are reviewed before new tools or workflows are adopted.',
  sr2: 'The firm considers confidentiality, vendor risk, and contractual exposure when evaluating AI solutions.',
  sr3: 'There is awareness of reputational, regulatory, and client trust implications tied to AI use.',
  sr4: 'Higher-risk client-facing or judgment-sensitive use cases would trigger additional oversight or review.',
  sr5: 'There is a practical approach to documentation, traceability, or review for AI-enabled decisions and workflows.',
  ps1: 'Leaders can communicate AI adoption in a way that reduces fear while protecting professional standards.',
  ps2: 'Teams have at least a baseline understanding of responsible AI use in their roles.',
  ps3: 'Training or guidance is available or planned for teams expected to use AI in client or internal workflows.',
  ps4: 'The firm can identify and support internal champions for AI adoption.',
  ps5: 'Change management is treated as part of AI implementation rather than a downstream issue.',
  wi1: 'The firm has identified workflows where AI could improve research, proposals, internal knowledge work, delivery support, or operations.',
  wi2: 'Potential AI use cases are prioritized based on client value, feasibility, and risk.',
  wi3: 'There are clear owners for embedding AI into actual delivery and support processes.',
  wi4: 'Success measures exist or could be defined for AI-enabled workflow improvements.',
  wi5: 'The firm can pilot AI in targeted workflows without losing accountability or delivery quality.',
  te1: 'The firm considers transparency, accountability, trust, and professional responsibility when evaluating AI use.',
  te2: 'There is clarity on when expert human review must remain in the loop for client-facing or high-risk outputs.',
  te3: 'Leaders think about client trust and professional standards, not just efficiency.',
  te4: 'Leadership would be able to explain how AI-assisted work is being used in sensitive delivery contexts.',
  te5: 'There is awareness that some AI use cases may be inappropriate for professional service work even if technically possible.',
};

export const INDUSTRY_QUESTION_SETS = {
  educationalInstitutions: replacePrompts(cloneBaseCategories(), educationalPrompts),
  nonprofits: replacePrompts(cloneBaseCategories(), nonprofitPrompts),
  smallBusinesses: replacePrompts(cloneBaseCategories(), smallBusinessPrompts),
  itTeams: replacePrompts(cloneBaseCategories(), itTeamPrompts),
  creativeTeams: replacePrompts(cloneBaseCategories(), creativePrompts),
  professionalServices: replacePrompts(cloneBaseCategories(), professionalPrompts),
};
